### PR TITLE
Update Pushsafer

### PR DESCRIPTION
**Pull request by appzer**
- add parameter confirm (CR)
- add two new sounds

### CODE REVIEW

**Comment by appzer** [comment]
do you also update the npm package?
Thanks Kevin

**Comment by Christchoper** [comment]
Hi FreeTimeCoder82,
It would be great if you could update the package. Thanks for the great node.
Cheers, Chris

**Comment by FreeTimeCoder82** [comment]
Hi,
I am currently working on a completely rewritten v2 of the nodes.
I will integrate your request in the updated version.
I hope I will be finished with this in 2-3 weeks, depending on my main job.
Thank you for your help and work.
Oliver

**Comment by appzer** [comment]
Hello, any news for an update?

**Pull request closed without merging**
